
twig:
    # используем тему для форм для bootstrap5
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        imagesFolder: '%images_folder%'

when@test:
    twig:
        strict_variables: true
